"""
Limit Order Book with price-time priority (FIFO) matching.

Bids are maintained sorted descending by price (max-bid first).
Asks are maintained sorted ascending by price (min-ask first).
When two orders have the same price, the one submitted earlier is matched first.
"""

from dataclasses import dataclass, field
import uuid


@dataclass(order=False)
class Order:
    """Represents a single resting or incoming order."""
    order_id: str
    agent_id: str
    side: str          # 'BID' or 'ASK'
    price: float
    quantity: int
    timestamp: int

    def __lt__(self, other):
        # For bids: higher price wins; for asks: lower price wins
        # Tie-break: earlier timestamp wins (FIFO)
        if self.side == "BID":
            if self.price != other.price:
                return self.price > other.price   # descending price
            return self.timestamp < other.timestamp
        else:
            if self.price != other.price:
                return self.price < other.price   # ascending price
            return self.timestamp < other.timestamp


class LimitOrderBook:
    """Price-time priority limit order book.

    Parameters
    ----------
    tick_size : float
        Minimum price increment (orders are rounded to this).
    """

    def __init__(self, tick_size: float = 0.001):
        self.tick_size = tick_size
        self._bids: list = []   # list of Order, kept sorted (best bid first)
        self._asks: list = []   # list of Order, kept sorted (best ask first)
        self.trade_history: list = []

    def _round_price(self, price: float) -> float:
        return round(price / self.tick_size) * self.tick_size

    def best_bid(self) -> float | None:
        return self._bids[0].price if self._bids else None

    def best_ask(self) -> float | None:
        return self._asks[0].price if self._asks else None

    def mid_price(self) -> float | None:
        bb = self.best_bid()
        ba = self.best_ask()
        if bb is None or ba is None:
            return None
        return (bb + ba) / 2.0

    def spread(self) -> float | None:
        bb = self.best_bid()
        ba = self.best_ask()
        if bb is None or ba is None:
            return None
        return ba - bb

    def snapshot(self) -> dict:
        """Return top-5 levels on each side."""
        bids = [(o.price, o.quantity) for o in self._bids[:5]]
        asks = [(o.price, o.quantity) for o in self._asks[:5]]
        return {
            "bids": bids,
            "asks": asks,
            "mid": self.mid_price(),
            "spread": self.spread(),
        }

    def add_limit_order(self, order: Order) -> list:
        """Submit a limit order; crosses book first, then rests remainder.

        Returns
        -------
        list[dict]
            Trade records generated by crossing.
        """
        order.price = self._round_price(order.price)
        trades = []

        if order.side == "BID":
            # Cross against asks
            while order.quantity > 0 and self._asks and self._asks[0].price <= order.price:
                resting = self._asks[0]
                fill_qty = min(order.quantity, resting.quantity)
                trade = {
                    "price": resting.price,
                    "quantity": fill_qty,
                    "buyer_id": order.agent_id,
                    "seller_id": resting.agent_id,
                    "timestamp": order.timestamp,
                }
                trades.append(trade)
                self.trade_history.append(trade)
                order.quantity -= fill_qty
                resting.quantity -= fill_qty
                if resting.quantity == 0:
                    self._asks.pop(0)

            if order.quantity > 0:
                self._insert_bid(order)

        else:  # ASK
            while order.quantity > 0 and self._bids and self._bids[0].price >= order.price:
                resting = self._bids[0]
                fill_qty = min(order.quantity, resting.quantity)
                trade = {
                    "price": resting.price,
                    "quantity": fill_qty,
                    "buyer_id": resting.agent_id,
                    "seller_id": order.agent_id,
                    "timestamp": order.timestamp,
                }
                trades.append(trade)
                self.trade_history.append(trade)
                order.quantity -= fill_qty
                resting.quantity -= fill_qty
                if resting.quantity == 0:
                    self._bids.pop(0)

            if order.quantity > 0:
                self._insert_ask(order)

        return trades

    def add_market_order(self, agent_id: str, side: str, quantity: int, timestamp: int) -> list:
        """Submit a market order; sweeps book until filled or book empty."""
        trades = []
        remaining = quantity

        if side == "BID":
            while remaining > 0 and self._asks:
                resting = self._asks[0]
                fill_qty = min(remaining, resting.quantity)
                trade = {
                    "price": resting.price,
                    "quantity": fill_qty,
                    "buyer_id": agent_id,
                    "seller_id": resting.agent_id,
                    "timestamp": timestamp,
                }
                trades.append(trade)
                self.trade_history.append(trade)
                remaining -= fill_qty
                resting.quantity -= fill_qty
                if resting.quantity == 0:
                    self._asks.pop(0)
        else:
            while remaining > 0 and self._bids:
                resting = self._bids[0]
                fill_qty = min(remaining, resting.quantity)
                trade = {
                    "price": resting.price,
                    "quantity": fill_qty,
                    "buyer_id": resting.agent_id,
                    "seller_id": agent_id,
                    "timestamp": timestamp,
                }
                trades.append(trade)
                self.trade_history.append(trade)
                remaining -= fill_qty
                resting.quantity -= fill_qty
                if resting.quantity == 0:
                    self._bids.pop(0)

        return trades

    def cancel_order(self, order_id: str) -> bool:
        """Remove an order by ID. Returns True if found and cancelled."""
        for lst in (self._bids, self._asks):
            for i, o in enumerate(lst):
                if o.order_id == order_id:
                    lst.pop(i)
                    return True
        return False

    def _insert_bid(self, order: Order) -> None:
        """Insert bid maintaining descending price, then ascending timestamp order."""
        lo, hi = 0, len(self._bids)
        while lo < hi:
            mid = (lo + hi) // 2
            b = self._bids[mid]
            if b.price > order.price or (b.price == order.price and b.timestamp < order.timestamp):
                lo = mid + 1
            else:
                hi = mid
        self._bids.insert(lo, order)

    def _insert_ask(self, order: Order) -> None:
        """Insert ask maintaining ascending price, then ascending timestamp order."""
        lo, hi = 0, len(self._asks)
        while lo < hi:
            mid = (lo + hi) // 2
            a = self._asks[mid]
            if a.price < order.price or (a.price == order.price and a.timestamp < order.timestamp):
                lo = mid + 1
            else:
                hi = mid
        self._asks.insert(lo, order)

    def get_trade_history(self):
        import pandas as pd
        if not self.trade_history:
            return pd.DataFrame(columns=["price", "quantity", "buyer_id", "seller_id", "timestamp"])
        return pd.DataFrame(self.trade_history)


def _new_order_id() -> str:
    return str(uuid.uuid4())[:8]
